//! Every Horde challenge deck's non-token card names must resolve in the card DB.
//!
//! `deck_loading::load_horde_library` PANICS on a name it cannot resolve — a
//! fixed engine resource with a typo would take the game down at load rather than
//! silently shipping a short library. That makes the decklists' spelling
//! load-bearing, and a transcription slip is the single most likely way to break
//! a deck (the lists are hand-copied from hordemagic.com).
//!
//! This is the class-level guard: it walks `ChallengeDeck::ALL` rather than
//! naming decks one at a time, so a NEW deck is covered the moment it is added —
//! no per-deck test to remember. `deck_nontoken_cards` below is an exhaustive
//! match, so adding a `ChallengeDeck` variant fails to compile until its list is
//! wired in here too.
//!
//! Skips when `client/public/card-data.json` is absent: it is gitignored (92MB,
//! generated by the card-data pipeline), so CI without it should not fail.

use std::path::Path;

use engine::database::card_db::CardDatabase;
use engine::game::deck_loading::load_horde_library;
use engine::types::format::{ChallengeDeck, FormatConfig};
use engine::types::game_state::GameState;

/// The generated full card database, or `None` when it has not been built.
fn full_card_db() -> Option<CardDatabase> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../client/public/card-data.json");
    if !path.exists() {
        eprintln!(
            "skipping: client/public/card-data.json not generated \
             (run the card-data pipeline to enable this check)"
        );
        return None;
    }
    Some(CardDatabase::from_export(&path).expect("card-data.json should load"))
}

/// Each deck's non-token `(count, name)` list. Exhaustive match: a new
/// `ChallengeDeck` variant will not compile until it is listed here.
fn deck_nontoken_cards(deck: ChallengeDeck) -> &'static [(u32, &'static str)] {
    use engine::game::decks;
    match deck {
        ChallengeDeck::CybermanHorde => decks::cyberman_horde::CYBERMAN_HORDE_NONTOKEN_CARDS,
        ChallengeDeck::DndHorde => decks::dnd_horde::DND_OOZE_NONTOKEN_CARDS,
        ChallengeDeck::ZombiesHorde => decks::zombies_horde::ZOMBIES_HORDE_NONTOKEN_CARDS,
        ChallengeDeck::SliversHorde => decks::slivers_horde::SLIVERS_HORDE_NONTOKEN_CARDS,
        ChallengeDeck::HumansGodzillaHorde => {
            decks::humans_godzilla_horde::HUMANS_GODZILLA_HORDE_NONTOKEN_CARDS
        }
        ChallengeDeck::SauronHorde => decks::sauron_horde::SAURON_HORDE_NONTOKEN_CARDS,
        ChallengeDeck::SarumanHorde => decks::saruman_horde::SARUMAN_HORDE_NONTOKEN_CARDS,
        // The combined "Two Towers" pairing loads Sauron's library at seat 0 (its
        // co-Horde Saruman library is covered by the `SarumanHorde` arm above), so
        // this name-resolution guard checks the same seat-0 list `load_horde_library`
        // resolves for it.
        ChallengeDeck::LotrTwoTowersHorde => decks::sauron_horde::SAURON_HORDE_NONTOKEN_CARDS,
    }
}

#[test]
fn every_horde_deck_nontoken_name_resolves_in_the_card_db() {
    let Some(db) = full_card_db() else {
        return;
    };

    let mut failures: Vec<String> = Vec::new();
    for &deck in ChallengeDeck::ALL {
        for (_, name) in deck_nontoken_cards(deck) {
            if db.get_face_by_name(name).is_none() {
                failures.push(format!("{deck:?}: '{name}'"));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "these Horde deck card names do not resolve in the card DB and would panic \
         at game load:\n  {}",
        failures.join("\n  ")
    );
}

/// Guards the guard: if the card DB loaded but somehow matched nothing, the test
/// above would pass vacuously. Assert a known-good name really does resolve.
#[test]
fn card_db_lookup_is_actually_working() {
    let Some(db) = full_card_db() else {
        return;
    };
    assert!(
        db.get_face_by_name("Island").is_some(),
        "positive control: a basic land must resolve, otherwise the name-resolution \
         check above proves nothing"
    );
}

/// The D&D Horde's rarity-based wave depends on each non-token library card
/// carrying a rarity. The runtime `card-data.json` export does NOT include rarity
/// (`CardFace::rarities` is empty), so the rarity is PINNED in the deck and
/// threaded through `create_horde_library_card`. This drives the REAL library
/// load and asserts EVERY non-token card ends up with a rarity — the wiring
/// guard for the live bug where a rarity-less wave revealed the entire library
/// every turn.
#[test]
fn dnd_horde_library_cards_all_carry_a_rarity() {
    let Some(db) = full_card_db() else {
        return;
    };
    let mut state = GameState::new(
        FormatConfig::horde(ChallengeDeck::DndHorde.default_ruleset()),
        2,
        42,
    );
    let horde = state.format_config.archenemy_player().expect("Horde seat");
    load_horde_library(&mut state, &db, horde, ChallengeDeck::DndHorde);

    let library: Vec<_> = state
        .players
        .iter()
        .find(|p| p.id == horde)
        .expect("horde player")
        .library
        .iter()
        .copied()
        .collect();

    let mut nontoken_cards = 0usize;
    let mut with_rarity = 0usize;
    let mut uncommon_or_better = 0usize;
    for id in &library {
        let obj = state.objects.get(id).expect("library object");
        if obj.is_token {
            continue;
        }
        nontoken_cards += 1;
        if let Some(r) = obj.horde_library_rarity {
            with_rarity += 1;
            if r >= engine::types::card::Rarity::Uncommon {
                uncommon_or_better += 1;
            }
        }
    }

    assert_eq!(
        nontoken_cards, 62,
        "D&D Ooze library has 62 non-token cards"
    );
    assert_eq!(
        with_rarity, nontoken_cards,
        "EVERY non-token D&D library card must carry a rarity — a rarity-less card \
         makes the UntilRarityAtLeast wave reveal the whole library"
    );
    assert!(
        uncommon_or_better > 0,
        "the library must contain uncommon-or-better cards so waves can terminate"
    );
}

/// Every deck must actually have cards — an empty list would make the
/// name-resolution test above pass trivially for that deck.
#[test]
fn every_horde_deck_has_a_nonempty_decklist() {
    for &deck in ChallengeDeck::ALL {
        let cards = deck_nontoken_cards(deck);
        assert!(
            !cards.is_empty(),
            "{deck:?} has an empty non-token decklist"
        );
        let total: u32 = cards.iter().map(|(count, _)| *count).sum();
        assert!(
            total >= 50,
            "{deck:?} has only {total} non-token cards — Horde libraries are ~100-150"
        );
    }
}
