//! Every Horde challenge deck's non-token card names must resolve in the card DB.
//!
//! `deck_loading::load_horde_library` PANICS on a name it cannot resolve — a
//! fixed engine resource with a typo would take the game down at load rather than
//! silently shipping a short library. That makes the decklists' spelling
//! load-bearing, and a transcription slip is the single most likely way to break
//! a deck (the lists are hand-copied from hordemagic.com).
//!
//! This is the class-level guard: it walks `ChallengeDeck::ALL` rather than
//! naming decks one at a time, so a NEW deck is covered the moment it is added —
//! no per-deck test to remember. `deck_nontoken_cards` below is an exhaustive
//! match, so adding a `ChallengeDeck` variant fails to compile until its list is
//! wired in here too.
//!
//! Skips when `client/public/card-data.json` is absent: it is gitignored (92MB,
//! generated by the card-data pipeline), so CI without it should not fail.

use std::path::Path;

use engine::database::card_db::CardDatabase;
use engine::types::format::ChallengeDeck;

/// The generated full card database, or `None` when it has not been built.
fn full_card_db() -> Option<CardDatabase> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../client/public/card-data.json");
    if !path.exists() {
        eprintln!(
            "skipping: client/public/card-data.json not generated \
             (run the card-data pipeline to enable this check)"
        );
        return None;
    }
    Some(CardDatabase::from_export(&path).expect("card-data.json should load"))
}

/// Each deck's non-token `(count, name)` list. Exhaustive match: a new
/// `ChallengeDeck` variant will not compile until it is listed here.
fn deck_nontoken_cards(deck: ChallengeDeck) -> &'static [(u32, &'static str)] {
    use engine::game::decks;
    match deck {
        ChallengeDeck::CybermanHorde => decks::cyberman_horde::CYBERMAN_HORDE_NONTOKEN_CARDS,
        ChallengeDeck::DndHorde => decks::dnd_horde::DND_OOZE_NONTOKEN_CARDS,
        ChallengeDeck::ZombiesHorde => decks::zombies_horde::ZOMBIES_HORDE_NONTOKEN_CARDS,
        ChallengeDeck::SliversHorde => decks::slivers_horde::SLIVERS_HORDE_NONTOKEN_CARDS,
        ChallengeDeck::HumansGodzillaHorde => {
            decks::humans_godzilla_horde::HUMANS_GODZILLA_HORDE_NONTOKEN_CARDS
        }
    }
}

#[test]
fn every_horde_deck_nontoken_name_resolves_in_the_card_db() {
    let Some(db) = full_card_db() else {
        return;
    };

    let mut failures: Vec<String> = Vec::new();
    for &deck in ChallengeDeck::ALL {
        for (_, name) in deck_nontoken_cards(deck) {
            if db.get_face_by_name(name).is_none() {
                failures.push(format!("{deck:?}: '{name}'"));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "these Horde deck card names do not resolve in the card DB and would panic \
         at game load:\n  {}",
        failures.join("\n  ")
    );
}

/// Guards the guard: if the card DB loaded but somehow matched nothing, the test
/// above would pass vacuously. Assert a known-good name really does resolve.
#[test]
fn card_db_lookup_is_actually_working() {
    let Some(db) = full_card_db() else {
        return;
    };
    assert!(
        db.get_face_by_name("Island").is_some(),
        "positive control: a basic land must resolve, otherwise the name-resolution \
         check above proves nothing"
    );
}

/// Every deck must actually have cards — an empty list would make the
/// name-resolution test above pass trivially for that deck.
#[test]
fn every_horde_deck_has_a_nonempty_decklist() {
    for &deck in ChallengeDeck::ALL {
        let cards = deck_nontoken_cards(deck);
        assert!(
            !cards.is_empty(),
            "{deck:?} has an empty non-token decklist"
        );
        let total: u32 = cards.iter().map(|(count, _)| *count).sum();
        assert!(
            total >= 50,
            "{deck:?} has only {total} non-token cards — Horde libraries are ~100-150"
        );
    }
}
